### ISSUE TITLE
[feature] jsx support

### ISSUE THREAD

**Issue by vovkasm** [dalcib/esbuild-plugin-flow#1]
Currently plugin always return loader 'js' for further processing, but some modules contains flowtype'd jsx code in '*.js' files...

**Comment by dalcib** [comment]
Thank you for pointing this out.
Do you think `/react/.test(source)` + `.js` is sufficient to identify when the JSX loader is needed?
Or it would be better simply to change `loader: 'js'` to `loader:'jsx'` for all files?

**Comment by vovkasm** [comment]
@dalcib , I just copy plugin code into build.js and changed loader to jsx for all files. I think this is safe enough at the current level of development. )
